import { CardDefinition } from './types';

export const CARD_CATALOG: readonly CardDefinition[] = [
  {
    id: 'bucket',
    name: 'Bucket',
    kind: 'unit',
    faction: 'universal',
    tier: 1,
    cost: 1,
    description: 'Fallback unit. Unremarkable, dependable, unavoidable.',
    attack: 1,
    health: 2,
  },
  {
    id: 'antlion-runner',
    name: 'Antlion Runner',
    kind: 'unit',
    faction: 'antlion',
    tier: 1,
    cost: 1,
    description: 'Fast low-cost lane pressure.',
    attack: 2,
    health: 1,
  },
  {
    id: 'antlion-worker',
    name: 'Antlion Worker',
    kind: 'unit',
    faction: 'antlion',
    tier: 2,
    cost: 3,
    description: 'Can spit acid at the opposing unit after surviving a turn.',
    attack: 2,
    health: 4,
    special: {
      name: 'Acid Spit',
      description: 'Deal 3 damage to an enemy unit.',
      cost: 2,
      uses: 2,
      target: 'enemy-unit',
      effects: [{ type: 'damage-unit', amount: 3 }],
    },
  },
  {
    id: 'antlion-guard',
    name: 'Antlion Guard',
    kind: 'unit',
    faction: 'antlion',
    tier: 3,
    cost: 5,
    description: 'Heavy creature with a destructive charge.',
    attack: 5,
    health: 7,
    special: {
      name: 'Final Charge',
      description: 'Destroy self to deal 7 damage to the opposing unit.',
      cost: 2,
      uses: 1,
      target: 'enemy-unit',
      effects: [{ type: 'damage-unit', amount: 7 }],
      destroySelfAfter: true,
    },
  },
  {
    id: 'combine-metrocop',
    name: 'Metrocop',
    kind: 'unit',
    faction: 'combine',
    tier: 1,
    cost: 2,
    description: 'Reliable Combine infantry.',
    attack: 2,
    health: 3,
  },
  {
    id: 'combine-soldier',
    name: 'Combine Soldier',
    kind: 'unit',
    faction: 'combine',
    tier: 2,
    cost: 4,
    description: 'Can reinforce a friendly unit.',
    attack: 4,
    health: 4,
    special: {
      name: 'Reinforce',
      description: 'Give a friendly unit +2 ATK and +1 HP.',
      cost: 2,
      uses: 2,
      target: 'friendly-unit',
      effects: [{ type: 'buff-unit', attack: 2, health: 1 }],
    },
  },
  {
    id: 'combine-elite',
    name: 'Combine Elite',
    kind: 'unit',
    faction: 'combine',
    tier: 3,
    cost: 6,
    description: 'Expensive finisher that can fire directly at the enemy hero.',
    attack: 6,
    health: 6,
    special: {
      name: 'Pulse Shot',
      description: 'Deal 3 direct hero damage.',
      cost: 3,
      uses: 1,
      target: 'enemy-hero',
      effects: [{ type: 'damage-hero', amount: 3 }],
    },
  },
  {
    id: 'rebel-scout',
    name: 'Rebel Scout',
    kind: 'unit',
    faction: 'rebel',
    tier: 1,
    cost: 1,
    description: 'Cheap rebel body.',
    attack: 1,
    health: 3,
  },
  {
    id: 'rebel-medic',
    name: 'Rebel Medic',
    kind: 'unit',
    faction: 'rebel',
    tier: 2,
    cost: 3,
    description: 'Keeps friendly units alive.',
    attack: 2,
    health: 4,
    special: {
      name: 'Field Treatment',
      description: 'Heal a friendly unit for 4.',
      cost: 2,
      uses: 2,
      target: 'friendly-unit',
      effects: [{ type: 'heal-unit', amount: 4 }],
    },
  },
  {
    id: 'rebel-veteran',
    name: 'Rebel Veteran',
    kind: 'unit',
    faction: 'rebel',
    tier: 3,
    cost: 5,
    description: 'Can rally an ally into a stronger threat.',
    attack: 4,
    health: 6,
    special: {
      name: 'Rally',
      description: 'Give a friendly unit +1 ATK and +3 HP.',
      cost: 2,
      uses: 2,
      target: 'friendly-unit',
      effects: [{ type: 'buff-unit', attack: 1, health: 3 }],
    },
  },
  {
    id: 'zombie-shambler',
    name: 'Shambler',
    kind: 'unit',
    faction: 'zombie',
    tier: 1,
    cost: 2,
    description: 'Slow but durable.',
    attack: 2,
    health: 4,
  },
  {
    id: 'zombie-fast',
    name: 'Fast Zombie',
    kind: 'unit',
    faction: 'zombie',
    tier: 2,
    cost: 3,
    description: 'Aggressive zombie that can mend itself.',
    attack: 4,
    health: 3,
    special: {
      name: 'Consume',
      description: 'Heal self for 3.',
      cost: 1,
      uses: 2,
      target: 'self',
      effects: [{ type: 'heal-unit', amount: 3 }],
    },
  },
  {
    id: 'zombie-poison',
    name: 'Poison Zombie',
    kind: 'unit',
    faction: 'zombie',
    tier: 3,
    cost: 5,
    description: 'A large source of persistent lane pressure.',
    attack: 4,
    health: 8,
  },
  {
    id: 'universal-mercenary',
    name: 'Mercenary',
    kind: 'unit',
    faction: 'universal',
    tier: 2,
    cost: 3,
    description: 'Universal unit that fits any lane.',
    attack: 3,
    health: 3,
  },
  {
    id: 'building-field-hospital',
    name: 'Field Hospital',
    kind: 'building',
    faction: 'rebel',
    tier: 2,
    cost: 3,
    description: 'At the start of your turn, heal your unit in this lane by 1.',
    passive: { type: 'heal-own-lane-unit-at-turn-start', amount: 1 },
  },
  {
    id: 'building-ammo-cache',
    name: 'Ammo Cache',
    kind: 'building',
    faction: 'combine',
    tier: 2,
    cost: 3,
    description: 'Your unit in this lane gets +1 attack while attacking.',
    passive: { type: 'attack-bonus-own-lane', amount: 1 },
  },
  {
    id: 'building-nest',
    name: 'Antlion Nest',
    kind: 'building',
    faction: 'antlion',
    tier: 2,
    cost: 2,
    description: 'Your unit in this lane gets +1 attack while attacking.',
    passive: { type: 'attack-bonus-own-lane', amount: 1 },
  },
  {
    id: 'building-grave-mound',
    name: 'Grave Mound',
    kind: 'building',
    faction: 'zombie',
    tier: 2,
    cost: 2,
    description: 'At the start of your turn, heal your unit in this lane by 1.',
    passive: { type: 'heal-own-lane-unit-at-turn-start', amount: 1 },
  },
  {
    id: 'power-strike',
    name: 'Focused Strike',
    kind: 'power',
    faction: 'universal',
    tier: 1,
    cost: 2,
    description: 'Deal 3 damage to an enemy unit.',
    target: 'enemy-unit',
    effects: [{ type: 'damage-unit', amount: 3 }],
  },
  {
    id: 'power-rally',
    name: 'Rally Order',
    kind: 'power',
    faction: 'rebel',
    tier: 2,
    cost: 2,
    description: 'Give a friendly unit +2 ATK and +2 HP.',
    target: 'friendly-unit',
    effects: [{ type: 'buff-unit', attack: 2, health: 2 }],
  },
  {
    id: 'power-shelling',
    name: 'Shelling',
    kind: 'power',
    faction: 'combine',
    tier: 3,
    cost: 4,
    description: 'Deal 4 damage directly to the enemy hero.',
    target: 'enemy-hero',
    effects: [{ type: 'damage-hero', amount: 4 }],
  },
  {
    id: 'power-sabotage',
    name: 'Sabotage',
    kind: 'power',
    faction: 'universal',
    tier: 2,
    cost: 2,
    description: 'Destroy an enemy building.',
    target: 'enemy-building',
    effects: [{ type: 'destroy-building' }],
  },
  {
    id: 'power-resupply',
    name: 'Resupply',
    kind: 'power',
    faction: 'universal',
    tier: 1,
    cost: 1,
    description: 'Draw 2 cards.',
    target: 'none',
    effects: [{ type: 'draw', amount: 2 }],
  },
];

export const CARD_BY_ID = new Map(CARD_CATALOG.map((card) => [card.id, card]));

export function getCard(cardId: string): CardDefinition {
  const card = CARD_BY_ID.get(cardId);
  if (!card) throw new Error(`Unknown card: ${cardId}`);
  return card;
}
