import { CardDefinition } from './types';

export const CARD_CATALOG: readonly CardDefinition[] = [
  {
    id: 'bucket',
    name: 'Bucket',
    kind: 'unit',
    faction: 'universal',
    tier: 1,
    cost: 1,
    description: 'Fallback unit. Unremarkable, dependable, unavoidable.',
    attack: 1,
    health: 2,
  },
  {
    id: 'antlion-runner',
    name: 'Antlion Runner',
    kind: 'unit',
    faction: 'antlion',
    tier: 1,
    cost: 1,
    description: 'Fast low-cost lane pressure.',
    attack: 2,
    health: 1,
  },
  {
    id: 'antlion-worker',
    name: 'Antlion Worker',
    kind: 'unit',
    faction: 'antlion',
    tier: 2,
    cost: 3,
    description: 'Can spit acid at the opposing unit after surviving a turn.',
    attack: 2,
    health: 4,
    special: {
      name: 'Acid Spit',
      description: 'Deal 3 damage to an enemy unit.',
      cost: 2,
      uses: 2,
      target: 'enemy-unit',
      effects: [{ type: 'damage-unit', amount: 3 }],
    },
  },
  {
    id: 'antlion-guard',
    name: 'Antlion Guard',
    kind: 'unit',
    faction: 'antlion',
    tier: 3,
    cost: 5,
    description: 'Heavy creature with a destructive charge.',
    attack: 5,
    health: 7,
    special: {
      name: 'Final Charge',
      description: 'Destroy self to deal 7 damage to the opposing unit.',
      cost: 2,
      uses: 1,
      target: 'enemy-unit',
      effects: [{ type: 'damage-unit', amount: 7 }],
      destroySelfAfter: true,
    },
  },
  {
    id: 'combine-metrocop',
    name: 'Metrocop',
    kind: 'unit',
    faction: 'combine',
    tier: 1,
    cost: 2,
    description: 'Reliable Combine infantry.',
    attack: 2,
    health: 3,
  },
  {
    id: 'combine-soldier',
    name: 'Combine Soldier',
    kind: 'unit',
    faction: 'combine',
    tier: 2,
    cost: 4,
    description: 'Can reinforce a friendly unit.',
    attack: 4,
    health: 4,
    special: {
      name: 'Reinforce',
      description: 'Give a friendly unit +2 ATK and +1 HP.',
      cost: 2,
      uses: 2,
      target: 'friendly-unit',
      effects: [{ type: 'buff-unit', attack: 2, health: 1 }],
    },
  },
  {
    id: 'combine-elite',
    name: 'Combine Elite',
    kind: 'unit',
    faction: 'combine',
    tier: 3,
    cost: 6,
    description: 'Expensive finisher that can fire directly at the enemy hero.',
    attack: 6,
    health: 6,
    special: {
      name: 'Pulse Shot',
      description: 'Deal 3 direct hero damage.',
      cost: 3,
      uses: 1,
      target: 'enemy-hero',
      effects: [{ type: 'damage-hero', amount: 3 }],
    },
  },
  {
    id: 'rebel-scout',
    name: 'Rebel Scout',
    kind: 'unit',
    faction: 'rebel',
    tier: 1,
    cost: 1,
    description: 'Cheap rebel body.',
    attack: 1,
    health: 3,
  },
  {
    id: 'rebel-medic',
    name: 'Rebel Medic',
    kind: 'unit',
    faction: 'rebel',
    tier: 2,
    cost: 3,
    description: 'Keeps friendly units alive.',
    attack: 2,
    health: 4,
    special: {
      name: 'Field Treatment',
      description: 'Heal a friendly unit for 4.',
      cost: 2,
      uses: 2,
      target: 'friendly-unit',
      effects: [{ type: 'heal-unit', amount: 4 }],
    },
  },
  {
    id: 'rebel-veteran',
    name: 'Rebel Veteran',
    kind: 'unit',
    faction: 'rebel',
    tier: 3,
    cost: 5,
    description: 'Can rally an ally into a stronger threat.',
    attack: 4,
    health: 6,
    special: {
      name: 'Rally',
      description: 'Give a friendly unit +1 ATK and +3 HP.',
      cost: 2,
      uses: 2,
      target: 'friendly-unit',
      effects: [{ type: 'buff-unit', attack: 1, health: 3 }],
    },
  },
  {
    id: 'zombie-shambler',
    name: 'Shambler',
    kind: 'unit',
    faction: 'zombie',
    tier: 1,
    cost: 2,
    description: 'Slow but durable.',
    attack: 2,
    health: 4,
  },
  {
    id: 'zombie-fast',
    name: 'Fast Zombie',
    kind: 'unit',
    faction: 'zombie',
    tier: 2,
    cost: 3,
    description: 'Aggressive zombie that can mend itself.',
    attack: 4,
    health: 3,
    special: {
      name: 'Consume',
      description: 'Heal self for 3.',
      cost: 1,
      uses: 2,
      target: 'self',
      effects: [{ type: 'heal-unit', amount: 3 }],
    },
  },
  {
    id: 'zombie-poison',
    name: 'Poison Zombie',
    kind: 'unit',
    faction: 'zombie',
    tier: 3,
    cost: 5,
    description: 'A large source of persistent lane pressure.',
    attack: 4,
    health: 8,
  },
  {
    id: 'universal-mercenary',
    name: 'Mercenary',
    kind: 'unit',
    faction: 'universal',
    tier: 2,
    cost: 3,
    description: 'Universal unit that fits any lane.',
    attack: 3,
    health: 3,
  },
  {
    id: 'antlion-tinker',
    name: 'Antlion Tinker',
    kind: 'unit',
    faction: 'antlion',
    tier: 2,
    cost: 3,
    description: 'Spits volatile acid at the opposing unit after surviving a turn.',
    attack: 4,
    health: 3,
    special: {
      name: 'Spitter',
      description: 'Deal 3 damage to an enemy unit.',
      cost: 1,
      uses: 1,
      target: 'enemy-unit',
      effects: [{ type: 'damage-unit', amount: 3 }],
    },
  },
  {
    id: 'combine-laser',
    name: 'Combine Laser',
    kind: 'unit',
    faction: 'combine',
    tier: 3,
    cost: 5,
    description: 'Anchors an ally with a targeting laser that sharpens their weapons.',
    attack: 3,
    health: 5,
    special: {
      name: 'Targeting Laser',
      description: 'Give a friendly unit +2 ATK and +0 HP.',
      cost: 1,
      uses: 1,
      target: 'friendly-unit',
      effects: [{ type: 'buff-unit', attack: 2, health: 0 }],
    },
  },
  {
    id: 'rebel-commander',
    name: 'Rebel Commander',
    kind: 'unit',
    faction: 'rebel',
    tier: 3,
    cost: 5,
    description: 'Leads the resistance and calls in reinforcements.',
    attack: 3,
    health: 5,
    special: {
      name: 'Morale',
      description: 'Draw 1 card.',
      cost: 1,
      uses: 1,
      target: 'none',
      effects: [{ type: 'draw', amount: 1 }],
    },
  },
  {
    id: 'zombie-bloater',
    name: 'Zombie Bloater',
    kind: 'unit',
    faction: 'zombie',
    tier: 2,
    cost: 3,
    description: 'A bloated horror that detonates on command, scorching the enemy hero.',
    attack: 2,
    health: 5,
    special: {
      name: 'Detonate',
      description: 'Detonate for 1 hero damage, then self-destruct.',
      cost: 1,
      uses: 1,
      target: 'enemy-hero',
      effects: [{ type: 'damage-hero', amount: 1 }],
      destroySelfAfter: true,
    },
  },
  {
    id: 'building-field-hospital',
    name: 'Field Hospital',
    kind: 'building',
    faction: 'rebel',
    tier: 2,
    cost: 3,
    description: 'At the start of your turn, heal your unit in this lane by 1.',
    passive: { type: 'heal-own-lane-unit-at-turn-start', amount: 1 },
  },
  {
    id: 'building-ammo-cache',
    name: 'Ammo Cache',
    kind: 'building',
    faction: 'combine',
    tier: 2,
    cost: 3,
    description: 'Your unit in this lane gets +1 attack while attacking.',
    passive: { type: 'attack-bonus-own-lane', amount: 1 },
  },
  {
    id: 'building-nest',
    name: 'Antlion Nest',
    kind: 'building',
    faction: 'antlion',
    tier: 2,
    cost: 2,
    description: 'Your unit in this lane gets +1 attack while attacking.',
    passive: { type: 'attack-bonus-own-lane', amount: 1 },
  },
  {
    id: 'building-grave-mound',
    name: 'Grave Mound',
    kind: 'building',
    faction: 'zombie',
    tier: 2,
    cost: 2,
    description: 'At the start of your turn, heal your unit in this lane by 1.',
    passive: { type: 'heal-own-lane-unit-at-turn-start', amount: 1 },
  },
  {
    id: 'building-bunker',
    name: 'Bunker',
    kind: 'building',
    faction: 'universal',
    tier: 3,
    cost: 4,
    description: 'Your unit in this lane gets +1 attack while attacking.',
    passive: { type: 'attack-bonus-own-lane', amount: 1 },
  },
  {
    id: 'power-strike',
    name: 'Focused Strike',
    kind: 'power',
    faction: 'universal',
    tier: 1,
    cost: 2,
    description: 'Deal 3 damage to an enemy unit.',
    target: 'enemy-unit',
    effects: [{ type: 'damage-unit', amount: 3 }],
  },
  {
    id: 'power-rally',
    name: 'Rally Order',
    kind: 'power',
    faction: 'rebel',
    tier: 2,
    cost: 2,
    description: 'Give a friendly unit +2 ATK and +2 HP.',
    target: 'friendly-unit',
    effects: [{ type: 'buff-unit', attack: 2, health: 2 }],
  },
  {
    id: 'power-shelling',
    name: 'Shelling',
    kind: 'power',
    faction: 'combine',
    tier: 3,
    cost: 4,
    description: 'Deal 4 damage directly to the enemy hero.',
    target: 'enemy-hero',
    effects: [{ type: 'damage-hero', amount: 4 }],
  },
  {
    id: 'power-sabotage',
    name: 'Sabotage',
    kind: 'power',
    faction: 'universal',
    tier: 2,
    cost: 2,
    description: 'Destroy an enemy building.',
    target: 'enemy-building',
    effects: [{ type: 'destroy-building' }],
  },
  {
    id: 'power-resupply',
    name: 'Resupply',
    kind: 'power',
    faction: 'universal',
    tier: 1,
    cost: 1,
    description: 'Draw 2 cards.',
    target: 'none',
    effects: [{ type: 'draw', amount: 2 }],
  },
  {
    id: 'power-berserk',
    name: 'Berserk',
    kind: 'power',
    faction: 'universal',
    tier: 2,
    cost: 2,
    description: 'Give a friendly unit +2 ATK and +0 HP.',
    target: 'friendly-unit',
    effects: [{ type: 'buff-unit', attack: 2, health: 0 }],
  },
  // ===========================================================================
  // Phase B primitives: debuff-unit, dot, aoe, add-card, gain-mana, heal-hero,
  // destroy-unit.
  // ===========================================================================
  {
    id: 'power-venom',
    name: 'Venom Spray',
    kind: 'power',
    faction: 'universal',
    tier: 1,
    cost: 2,
    description: 'Poison a unit: deal 2 damage at the start of each of its owner\'s next 2 turns.',
    target: 'enemy-unit',
    effects: [{ type: 'dot', amount: 2, turns: 2 }],
  },
  {
    id: 'power-rot',
    name: 'Rot',
    kind: 'power',
    faction: 'zombie',
    tier: 1,
    cost: 2,
    description: 'Rot a unit: deal 1 damage at the start of each of its owner\'s next 3 turns.',
    target: 'enemy-unit',
    effects: [{ type: 'dot', amount: 1, turns: 3 }],
  },
  {
    id: 'power-scorch',
    name: 'Scorched Earth',
    kind: 'power',
    faction: 'universal',
    tier: 2,
    cost: 3,
    description: 'Deal 2 damage to every unit in a lane — both sides.',
    target: 'lane',
    effects: [{ type: 'aoe', amount: 2 }],
  },
  {
    id: 'power-mend',
    name: 'Emergency Medkit',
    kind: 'power',
    faction: 'universal',
    tier: 1,
    cost: 2,
    description: 'Restore 3 HP to your hero (up to maximum).',
    target: 'none',
    effects: [{ type: 'heal-hero', amount: 3 }],
  },
  {
    id: 'power-overcharge',
    name: 'Overcharge',
    kind: 'power',
    faction: 'combine',
    tier: 1,
    cost: 1,
    description: 'Gain 2 mana (up to your maximum).',
    target: 'none',
    effects: [{ type: 'gain-mana', amount: 2 }],
  },
  {
    id: 'power-salvage',
    name: 'Salvage Run',
    kind: 'power',
    faction: 'universal',
    tier: 2,
    cost: 3,
    description: 'Add a Mercenary to your hand (lost if your hand is full).',
    target: 'none',
    effects: [{ type: 'add-card', cardId: 'universal-mercenary' }],
  },
  {
    id: 'power-execution',
    name: 'Execution Protocol',
    kind: 'power',
    faction: 'combine',
    tier: 3,
    cost: 5,
    description: 'Destroy an enemy unit.',
    target: 'enemy-unit',
    effects: [{ type: 'destroy-unit' }],
  },
  {
    id: 'power-wither',
    name: 'Wither Toxin',
    kind: 'power',
    faction: 'antlion',
    tier: 2,
    cost: 2,
    description: 'Reduce an enemy unit\'s attack by 2 and deal 1 damage to it.',
    target: 'enemy-unit',
    effects: [{ type: 'debuff-unit', attack: 2, health: 1 }],
  },
  {
    id: 'antlion-spitter',
    name: 'Antlion Spitter',
    kind: 'unit',
    faction: 'antlion',
    tier: 3,
    cost: 4,
    description: 'Coats its prey in a venom that lingers.',
    attack: 3,
    health: 5,
    special: {
      name: 'Venom Coating',
      description: 'Poison an enemy unit: 2 damage at the start of each of its owner\'s next 2 turns.',
      cost: 2,
      uses: 1,
      target: 'enemy-unit',
      effects: [{ type: 'dot', amount: 2, turns: 2 }],
    },
  },
  {
    id: 'rebel-engineer',
    name: 'Rebel Engineer',
    kind: 'unit',
    faction: 'rebel',
    tier: 3,
    cost: 4,
    description: 'Keeps the resistance standing, hero included.',
    attack: 3,
    health: 4,
    special: {
      name: 'Field Medkit',
      description: 'Restore 2 HP to your hero (up to maximum).',
      cost: 1,
      uses: 2,
      target: 'none',
      effects: [{ type: 'heal-hero', amount: 2 }],
    },
  },
  {
    id: 'combine-drone',
    name: 'Power Drone',
    kind: 'unit',
    faction: 'combine',
    tier: 2,
    cost: 3,
    description: 'A buzzing relay that taps the Combine grid.',
    attack: 1,
    health: 3,
    special: {
      name: 'Overtap',
      description: 'Gain 2 mana (up to your maximum).',
      cost: 1,
      uses: 2,
      target: 'none',
      effects: [{ type: 'gain-mana', amount: 2 }],
    },
  },
  // ===========================================================================
  // Phase C: catalog expansion to 60 cards. Reuses only the existing primitives
  // and card fields; no engine changes.
  // ===========================================================================
  {
    id: 'antlion-swarm',
    name: 'Bug Swarm',
    kind: 'unit',
    faction: 'antlion',
    tier: 1,
    cost: 2,
    description: 'Cheap swarming pressure.',
    attack: 3,
    health: 2,
  },
  {
    id: 'antlion-hunter',
    name: 'Antlion Hunter',
    kind: 'unit',
    faction: 'antlion',
    tier: 2,
    cost: 3,
    description: 'Snaps its prey in half before it lands.',
    attack: 4,
    health: 3,
    special: {
      name: 'Pincer Grip',
      description: "Reduce an enemy unit's attack by 1 and deal 2 damage to it.",
      cost: 2,
      uses: 1,
      target: 'enemy-unit',
      effects: [{ type: 'debuff-unit', attack: 1, health: 2 }],
    },
  },
  {
    id: 'antlion-queen',
    name: 'Antlion Queen',
    kind: 'unit',
    faction: 'antlion',
    tier: 3,
    cost: 6,
    description: 'Lays eggs that hatch into fresh swarms.',
    attack: 4,
    health: 8,
    special: {
      name: 'Lay Eggs',
      description: 'Add a Bug Swarm to your hand (lost if your hand is full).',
      cost: 2,
      uses: 2,
      target: 'none',
      effects: [{ type: 'add-card', cardId: 'antlion-swarm' }],
    },
  },
  {
    id: 'building-larva-pool',
    name: 'Larva Pool',
    kind: 'building',
    faction: 'antlion',
    tier: 2,
    cost: 3,
    description: 'At the start of your turn, heal your unit in this lane by 1.',
    passive: { type: 'heal-own-lane-unit-at-turn-start', amount: 1 },
  },
  {
    id: 'power-acid-rain',
    name: 'Acid Rain',
    kind: 'power',
    faction: 'antlion',
    tier: 2,
    cost: 4,
    description: 'Deal 2 damage to every unit in a lane — both sides.',
    target: 'lane',
    effects: [{ type: 'aoe', amount: 2 }],
  },
  {
    id: 'combine-juggernaut',
    name: 'Combine Juggernaut',
    kind: 'unit',
    faction: 'combine',
    tier: 3,
    cost: 8,
    description: 'An unstoppable armored finisher.',
    attack: 7,
    health: 9,
    special: {
      name: 'Purge Protocol',
      description: 'Destroy an enemy unit.',
      cost: 3,
      uses: 1,
      target: 'enemy-unit',
      effects: [{ type: 'destroy-unit' }],
    },
  },
  {
    id: 'building-power-substation',
    name: 'Power Substation',
    kind: 'building',
    faction: 'combine',
    tier: 2,
    cost: 4,
    description: 'Your unit in this lane gets +2 attack while attacking.',
    passive: { type: 'attack-bonus-own-lane', amount: 2 },
  },
  {
    id: 'rebel-guerrilla',
    name: 'Guerrilla',
    kind: 'unit',
    faction: 'rebel',
    tier: 1,
    cost: 2,
    description: 'Cheap, stubborn lane pressure.',
    attack: 2,
    health: 3,
  },
  {
    id: 'rebel-ambusher',
    name: 'Ambusher',
    kind: 'unit',
    faction: 'rebel',
    tier: 2,
    cost: 4,
    description: 'Strikes from the brush with a venomous blade.',
    attack: 4,
    health: 3,
    special: {
      name: 'Viper Fangs',
      description: "Poison an enemy unit: 2 damage at the start of each of its owner's next 2 turns.",
      cost: 2,
      uses: 1,
      target: 'enemy-unit',
      effects: [{ type: 'dot', amount: 2, turns: 2 }],
    },
  },
  {
    id: 'building-supply-drop',
    name: 'Supply Drop',
    kind: 'building',
    faction: 'rebel',
    tier: 2,
    cost: 4,
    description: 'At the start of your turn, heal your unit in this lane by 2.',
    passive: { type: 'heal-own-lane-unit-at-turn-start', amount: 2 },
  },
  {
    id: 'power-medic-convoy',
    name: 'Medic Convoy',
    kind: 'power',
    faction: 'rebel',
    tier: 2,
    cost: 3,
    description: 'Restore 5 HP to your hero (up to maximum).',
    target: 'none',
    effects: [{ type: 'heal-hero', amount: 5 }],
  },
  {
    id: 'power-landmine',
    name: 'Landmine',
    kind: 'power',
    faction: 'rebel',
    tier: 1,
    cost: 2,
    description: 'Deal 3 damage to every unit in a lane — both sides.',
    target: 'lane',
    effects: [{ type: 'aoe', amount: 3 }],
  },
  {
    id: 'zombie-ghoul',
    name: 'Ghoul',
    kind: 'unit',
    faction: 'zombie',
    tier: 1,
    cost: 3,
    description: 'Hungry and relentless.',
    attack: 3,
    health: 4,
  },
  {
    id: 'zombie-plague',
    name: 'Plague Bearer',
    kind: 'unit',
    faction: 'zombie',
    tier: 2,
    cost: 4,
    description: 'Its breath spreads a festering infection.',
    attack: 2,
    health: 5,
    special: {
      name: 'Spread Plague',
      description: "Poison an enemy unit: 3 damage at the start of each of its owner's next 2 turns.",
      cost: 2,
      uses: 1,
      target: 'enemy-unit',
      effects: [{ type: 'dot', amount: 3, turns: 2 }],
    },
  },
  {
    id: 'zombie-brute',
    name: 'Zombie Brute',
    kind: 'unit',
    faction: 'zombie',
    tier: 3,
    cost: 5,
    description: 'A hulking mass of rotting muscle.',
    attack: 5,
    health: 6,
    special: {
      name: 'Rotting Grasp',
      description: "Reduce an enemy unit's attack by 2 and deal 1 damage to it.",
      cost: 2,
      uses: 1,
      target: 'enemy-unit',
      effects: [{ type: 'debuff-unit', attack: 2, health: 1 }],
    },
  },
  {
    id: 'zombie-titan',
    name: 'Zombie Titan',
    kind: 'unit',
    faction: 'zombie',
    tier: 3,
    cost: 7,
    description: 'A towering wall of the undead.',
    attack: 6,
    health: 10,
  },
  {
    id: 'building-tomb',
    name: 'Tomb',
    kind: 'building',
    faction: 'zombie',
    tier: 2,
    cost: 4,
    description: 'At the start of your turn, heal your unit in this lane by 2.',
    passive: { type: 'heal-own-lane-unit-at-turn-start', amount: 2 },
  },
  {
    id: 'power-extermination',
    name: 'Extermination',
    kind: 'power',
    faction: 'zombie',
    tier: 3,
    cost: 6,
    description: 'Destroy an enemy unit.',
    target: 'enemy-unit',
    effects: [{ type: 'destroy-unit' }],
  },
  {
    id: 'universal-guard',
    name: 'Guard',
    kind: 'unit',
    faction: 'universal',
    tier: 1,
    cost: 2,
    description: 'A sturdy wall for any lane.',
    attack: 1,
    health: 4,
  },
  {
    id: 'power-overclock',
    name: 'Overclock',
    kind: 'power',
    faction: 'universal',
    tier: 2,
    cost: 2,
    description: 'Gain 3 mana (up to your maximum).',
    target: 'none',
    effects: [{ type: 'gain-mana', amount: 3 }],
  },
  // ===========================================================================
  // END-1: two new selectable lane factions — Guardian (defensive: heal/buff,
  // sturdy low-attack bodies) and Wraith (aggressive: damage/debuff, fast
  // fragile bodies). Data only; the engine is unchanged.
  // ===========================================================================
  {
    id: 'guardian-sentinel',
    name: 'Guardian Sentinel',
    kind: 'unit',
    faction: 'guardian',
    tier: 1,
    cost: 1,
    description: 'A patient wall of stone and light.',
    attack: 1,
    health: 5,
  },
  {
    id: 'guardian-priest',
    name: 'Guardian Priest',
    kind: 'unit',
    faction: 'guardian',
    tier: 2,
    cost: 3,
    description: 'Mends wounds with a steady, glowing hand.',
    attack: 2,
    health: 5,
    special: {
      name: 'Blessing',
      description: 'Heal a friendly unit for 4.',
      cost: 2,
      uses: 2,
      target: 'friendly-unit',
      effects: [{ type: 'heal-unit', amount: 4 }],
    },
  },
  {
    id: 'guardian-bulwark',
    name: 'Guardian Bulwark',
    kind: 'unit',
    faction: 'guardian',
    tier: 3,
    cost: 5,
    description: 'An unbreakable rampart that hardens its allies.',
    attack: 2,
    health: 7,
    special: {
      name: 'Fortify',
      description: 'Give a friendly unit +0 ATK and +4 HP.',
      cost: 2,
      uses: 1,
      target: 'friendly-unit',
      effects: [{ type: 'buff-unit', attack: 0, health: 4 }],
    },
  },
  {
    id: 'building-sacred-shrine',
    name: 'Sacred Shrine',
    kind: 'building',
    faction: 'guardian',
    tier: 2,
    cost: 3,
    description: 'At the start of your turn, heal your unit in this lane by 1.',
    passive: { type: 'heal-own-lane-unit-at-turn-start', amount: 1 },
  },
  {
    id: 'power-sacred-light',
    name: 'Sacred Light',
    kind: 'power',
    faction: 'guardian',
    tier: 1,
    cost: 2,
    description: 'Restore 3 HP to your hero (up to maximum).',
    target: 'none',
    effects: [{ type: 'heal-hero', amount: 3 }],
  },
  {
    id: 'power-holy-shield',
    name: 'Holy Shield',
    kind: 'power',
    faction: 'guardian',
    tier: 2,
    cost: 3,
    description: 'Give a friendly unit +0 ATK and +3 HP.',
    target: 'friendly-unit',
    effects: [{ type: 'buff-unit', attack: 0, health: 3 }],
  },
  {
    id: 'wraith-stalker',
    name: 'Wraith Stalker',
    kind: 'unit',
    faction: 'wraith',
    tier: 1,
    cost: 2,
    description: 'Strikes before it can be seen.',
    attack: 4,
    health: 1,
  },
  {
    id: 'wraith-reaper',
    name: 'Wraith Reaper',
    kind: 'unit',
    faction: 'wraith',
    tier: 2,
    cost: 3,
    description: 'Its touch withers flesh.',
    attack: 3,
    health: 2,
    special: {
      name: 'Death Touch',
      description: 'Deal 3 damage to an enemy unit.',
      cost: 1,
      uses: 2,
      target: 'enemy-unit',
      effects: [{ type: 'damage-unit', amount: 3 }],
    },
  },
  {
    id: 'wraith-lord',
    name: 'Wraith Lord',
    kind: 'unit',
    faction: 'wraith',
    tier: 3,
    cost: 5,
    description: 'A hollow crown that drinks the strength of the living.',
    attack: 5,
    health: 3,
    special: {
      name: 'Consuming Gaze',
      description: "Reduce an enemy unit's attack by 2 and deal 2 damage to it.",
      cost: 2,
      uses: 1,
      target: 'enemy-unit',
      effects: [{ type: 'debuff-unit', attack: 2, health: 2 }],
    },
  },
  {
    id: 'building-wraith-alter',
    name: 'Wraith Altar',
    kind: 'building',
    faction: 'wraith',
    tier: 2,
    cost: 3,
    description: 'Your unit in this lane gets +1 attack while attacking.',
    passive: { type: 'attack-bonus-own-lane', amount: 1 },
  },
  {
    id: 'power-haunt',
    name: 'Haunt',
    kind: 'power',
    faction: 'wraith',
    tier: 1,
    cost: 2,
    description: 'Haunt a unit: deal 2 damage at the start of each of its owner\'s next 2 turns.',
    target: 'enemy-unit',
    effects: [{ type: 'dot', amount: 2, turns: 2 }],
  },
  {
    id: 'power-soul-theft',
    name: 'Soul Theft',
    kind: 'power',
    faction: 'wraith',
    tier: 3,
    cost: 4,
    description: "Reduce an enemy unit's attack by 1, deal 2 damage to it, and restore 2 HP to your hero.",
    target: 'enemy-unit',
    effects: [
      { type: 'debuff-unit', attack: 1, health: 2 },
      { type: 'heal-hero', amount: 2 },
    ],
  },
  // =====================================================================
  // M2 gameplay pass: 15 new cards (2 powers, 13 units — 11 plain, 2 with
  // special abilities). Uses the stun/bounce/discard-random/onPlay/swarm/
  // drawOnKill/dot primitives. Factions: 4 universal, 3 antlion, 2 combine,
  // 2 rebel, 2 zombie, 1 wraith, 1 guardian.
  // =====================================================================
  {
    id: 'power-stasis-field',
    name: 'Stasis Field',
    kind: 'power',
    faction: 'universal',
    tier: 2,
    cost: 2,
    description: 'Stun an enemy unit: it skips its next attack.',
    target: 'enemy-unit',
    effects: [{ type: 'stun', turns: 1 }],
  },
  {
    id: 'power-terror-raid',
    name: 'Terror Raid',
    kind: 'power',
    faction: 'universal',
    tier: 2,
    cost: 2,
    description: 'Terrorize the enemy: they discard 2 random cards.',
    target: 'none',
    effects: [{ type: 'discard-random', amount: 2 }],
  },
  {
    id: 'universal-demolition-volunteer',
    name: 'Demolition Volunteer',
    kind: 'unit',
    faction: 'universal',
    tier: 1,
    cost: 2,
    description: 'A packed charge that grows stronger with every ally beside it.',
    attack: 3,
    health: 2,
    swarm: 1,
  },
  {
    id: 'universal-drill-sergeant',
    name: 'Drill Sergeant',
    kind: 'unit',
    faction: 'universal',
    tier: 1,
    cost: 1,
    description: 'Hurls a rallying order the moment they take the field: +1/+1 to itself.',
    attack: 1,
    health: 3,
    onPlay: { target: 'self', effects: [{ type: 'buff-unit', attack: 1, health: 1 }] },
  },
  {
    id: 'antlion-tunnel-harrier',
    name: 'Tunnel Harrier',
    kind: 'unit',
    faction: 'antlion',
    tier: 1,
    cost: 1,
    description: 'Rushes from the burrow to sap its prey\'s strength on impact: -1 ATK to the enemy unit.',
    attack: 2,
    health: 1,
    onPlay: { target: 'enemy-unit', effects: [{ type: 'debuff-unit', attack: 1, health: 0 }] },
  },
  {
    id: 'antlion-chitin-skirmisher',
    name: 'Chitin Skirmisher',
    kind: 'unit',
    faction: 'antlion',
    tier: 2,
    cost: 3,
    description: 'A hardened raider that cracks its prey on impact: -2 ATK to the enemy unit.',
    attack: 3,
    health: 2,
    onPlay: { target: 'enemy-unit', effects: [{ type: 'debuff-unit', attack: 2, health: 0 }] },
  },
  {
    id: 'antlion-nectar-swarm',
    name: 'Nectar Swarm',
    kind: 'unit',
    faction: 'antlion',
    tier: 1,
    cost: 2,
    description: 'A chattering cloud that swells with every ally nearby.',
    attack: 2,
    health: 2,
    swarm: 2,
  },
  {
    id: 'combine-riot-marshal',
    name: 'Metro Riot Marshal',
    kind: 'unit',
    faction: 'combine',
    tier: 2,
    cost: 4,
    description: 'Calls in reinforcements the instant they take command: draw 1.',
    attack: 4,
    health: 3,
    onPlay: { target: 'none', effects: [{ type: 'draw', amount: 1 }] },
  },
  {
    id: 'combine-metro-bouncer',
    name: 'Metro Bouncer',
    kind: 'unit',
    faction: 'combine',
    tier: 3,
    cost: 5,
    description: 'Ejects the chosen enemy unit back into its owner\'s hand.',
    attack: 4,
    health: 4,
    special: {
      name: 'Bounce',
      description: 'Bounce an enemy unit to its owner\'s hand.',
      cost: 2,
      uses: 1,
      target: 'enemy-unit',
      effects: [{ type: 'bounce-unit' }],
    },
  },
  {
    id: 'rebel-propaganda-runner',
    name: 'Propaganda Runner',
    kind: 'unit',
    faction: 'rebel',
    tier: 1,
    cost: 2,
    description: 'Broadcasts a defiant message that stings the enemy hero: 1 hero damage on play.',
    attack: 2,
    health: 3,
    onPlay: { target: 'enemy-hero', effects: [{ type: 'damage-hero', amount: 1 }] },
  },
  {
    id: 'rebel-wrench-tinker',
    name: 'Wrench Tinker',
    kind: 'unit',
    faction: 'rebel',
    tier: 2,
    cost: 3,
    description: 'When it destroys an enemy unit in combat, it scrambles a spare part into your hand: draw 1.',
    attack: 2,
    health: 3,
    drawOnKill: 1,
  },
  {
    id: 'zombie-rotting-warden',
    name: 'Rotting Warden',
    kind: 'unit',
    faction: 'zombie',
    tier: 2,
    cost: 3,
    description: 'Coats its target in festering rot: 2 damage at the start of each of its owner\'s next 2 turns.',
    attack: 2,
    health: 3,
    onPlay: { target: 'enemy-unit', effects: [{ type: 'dot', amount: 2, turns: 2 }] },
  },
  {
    id: 'zombie-plague-bearer',
    name: 'Plague Bearer',
    kind: 'unit',
    faction: 'zombie',
    tier: 2,
    cost: 4,
    description: 'Releases a virulent spore that poisons its target: 3 damage for 2 turns.',
    attack: 3,
    health: 4,
    onPlay: { target: 'enemy-unit', effects: [{ type: 'dot', amount: 3, turns: 2 }] },
  },
  {
    id: 'wraith-phantom-harrier',
    name: 'Phantom Harrier',
    kind: 'unit',
    faction: 'wraith',
    tier: 1,
    cost: 2,
    description: 'Grasps its target in a chill that steals its next attack: stun 1.',
    attack: 2,
    health: 2,
    onPlay: { target: 'enemy-unit', effects: [{ type: 'stun', turns: 1 }] },
  },
  {
    id: 'guardian-sacred-sentinel',
    name: 'Sacred Sentinel',
    kind: 'unit',
    faction: 'guardian',
    tier: 3,
    cost: 6,
    description: 'Draws a halo of divine protection over its own frame.',
    attack: 4,
    health: 6,
    special: {
      name: 'Aegis',
      description: 'Bless itself: +2/+2.',
      cost: 3,
      uses: 1,
      target: 'self',
      effects: [{ type: 'buff-unit', attack: 2, health: 2 }],
    },
  },
];

export const CARD_BY_ID = new Map(CARD_CATALOG.map((card) => [card.id, card]));

export function getCard(cardId: string): CardDefinition {
  const card = CARD_BY_ID.get(cardId);
  if (!card) throw new Error(`Unknown card: ${cardId}`);
  return card;
}
